name: Cache & install dependencies
description: This action caches and installs dependencies.
runs:
  using: "composite" # for the custom action this command is mandatory, it tells the action to use a composite run steps action
  steps:
    - name: cache node dependencies
      id: cache
      uses: actions/cache@v3
      with:
        # path: ~/.npm
        path: node_modules # will cache the node_modules folder instead of the ~/.npm folder
        key: node-dependencies-${{ hashFiles('**/package-lock.json') }}
    - name: install dependencies
      if: steps.cache.outputs.cache-hit != 'true' # this step will run only if the cache is not hit
      run: npm ci
      shell: bash
